[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
waku = { path = "../../waku-bindings", package = "waku-bindings" }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
