[package]
name = "tic-tac-toe"
version = "0.1.0"
edition = "2021"

[dependencies]
termcolor = "0.3"
waku = { path = "../../waku-bindings", package = "waku-bindings" }
serde_json = "1.0"
ark-std = "0.4"
ctrlc = "3.2.4"
